# Generated by Django 4.2.3 on 2023-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('wood', 'wood'), ('size', 'size')], max_length=100),
        ),
    ]
