# Generated by Django 4.2.3 on 2023-07-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
